### ISSUE TITLE
Hello, can you provide the complete project structure and environment?

### ISSUE THREAD

**Issue by 0xTyche** [schmittms/cell_force_prediction#1]
Thank you

**Comment by schmittms** [comment]
Hi,

What sort of project structure are you looking for? The jupyter notebooks are self-contained and have everything I used to train the models. For actual training, I just have an intermediate script that parses arguments and sends the job to our computing cluster, I don't think these would be of much use.

I've added the yaml file from our virtual environment used for this project. The packages in this venv are relatively old, but I have run these notebooks with updated versions of pytorch/numpy/etc. and it still works. So I would advise creating your own environment with a more up to date version of pytorch.

**Comment by 0xTyche** [comment]
Thank you very much for your response. While running load_trained_unet.ipy, I noticed that I was missing '../tensorboard_logs/220712_1418_0/model.pt', so I added it manually, and I'm curious if there are any other files in that directory. I also wanted to ask if the TractionData_All_16kpa_new data file is the same as the TractionData_All_16kpa data file. Could you also provide the versions of various packages such as PyTorch?

**Comment by schmittms** [comment]
Yes, sorry for the confusion: the TractionData_All_16kpa_new is the same as TractionData_All_16kpa. 
The package versions are listed in the yaml file, but here are the main ones:
```
pandas                    1.2.3           
pytorch                   1.10.0
cudatoolkit               10.2.89
numpy                     1.21.6
matplotlib                3.3.4
tensorboard               2.8.0
scipy                     1.6.2
scikit-learn              0.24.2
scikit-image              0.18.1  
```
However, I have also been able to run the code using a different environment with newer versions of all these packages. I would recommend using newer packages if possible because most of these are quite old. If anything breaks when you do so, please let me know.
